### ISSUE TITLE
Duplicate bookings

### ISSUE THREAD

**Issue by IElgohary** [SEGUC17/git-rekt-se#242]
**1. Severity:** 
medium
**2. Reported by:** 
Islam Elgohary
**3. Description:**
The client can make the exact same booking with the same info, pay for it and it can also be confirmed by the business.
**4. Steps to reproduce the issue:**
 1) as a business, create a service with an offering
 2) as a client, make a booking for the offering
 3) as a client make the same booking again 
 4) as a business, both bookings can be confirmed

**5. Expected result:**
 a. The user shouldn't be able to make the exact same booking twice in the first place.
 b. The Business shouldn't be able to confirm the exact booking twice

**Comment by Medo3G** [comment]
This is intended behaviour. You might be booking for someone else using your account for example.

**Comment by IElgohary** [comment]
this would lead to a problem in weak connections.
the client would pay twice for the same exact booking not knowing if it was submitted or not.

**Comment by Omarkojak** [comment]
@IElgohary i think that this is not a problem you will receive an email confirming your booking 
So two scenarios:-
First if you want to prevent the client from making two or more booking that is a bad UX as he can pay for one of his family members 
Second if you want just to add a warning the severity should be low since it's a frontend issue
